# Generated by Django 2.0.5 on 2018-08-01 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='subject',
        ),
    ]
