# Generated by Django 2.0.5 on 2018-08-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0002_auto_20180801_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='problemnumeral',
            name='explanation',
            field=models.TextField(default=''),
        ),
    ]
