# Generated by Django 2.0.5 on 2018-08-01 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opp', '0003_problemnumeral_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='number_of_steps',
        ),
        migrations.AlterField(
            model_name='problem',
            name='template',
            field=models.CharField(default='', max_length=500, verbose_name='Problem Template'),
        ),
        migrations.AlterField(
            model_name='problemnumeral',
            name='explanation',
            field=models.TextField(default=' '),
        ),
        migrations.AlterField(
            model_name='problemnumeral',
            name='question',
            field=models.TextField(default=' '),
        ),
    ]
